Cargo.lock, crates/backend/Cargo.toml, crates/backend/src/env.rs, crates/backend/src/main.rs
Sorry I re-open this here from another branch. Had some troubles.
=> Add environment variable parsing for backend

packages/playground/src/app/Console/index.tsx, packages/playground/src/context/index.tsx, packages/playground/src/context/set-dark-mode.ts, packages/playground/src/style/global.css, packages/playground/src/style/tailwind.css, packages/playground/tailwind.config.js
This PR implemets the dark mode as defult, using the tailwind "class" approach.
Tasks:
=> Implement dark mode

packages/components/package.json, packages/playground/__tests__/Header.test.tsx, yarn.lock
This PR enhances the header test, testing more like a user would use header and context.
=> Better testing of the header component

packages/playground/src/api/compile.ts, packages/playground/src/env.ts
=> Make COMPILE_URL optional

.gitignore, Makefile, packages/components/package.json, packages/playground/package.json
This PR does not resolve the full issue #79, but adds scripts to collect ts test coverage
=> Add scripts to collect ts test coverage

packages/docker-tests/__tests__/docker.test.ts
On my PR I had a failure because of this.
=> Set jest timeout to 30s

crates/backend/src/main.rs, crates/backend/src/services/gist/create.rs, crates/backend/src/services/gist/load.rs
Add better logging in backend
- for successfull interactions with the GH Gist API
- for services that are activated conditionally on startup
=> Add better logging in backend

.cspell.json, packages/playground/src/app/Header/index.tsx
=> Download feature

packages/playground/src/app/Editor/index.tsx, packages/playground/src/app/Editor/utils/startRustAnalyzer.ts
Small PR which only add logging of Rust Analyzer Status to the console
=> Rust analyzer console

packages/components/__tests__/ButtonWithIcon.test.tsx, packages/components/src/ButtonWithIcon.tsx, packages/playground/package.json, packages/playground/tailwind.config.js, packages/playground/webpack.config.js, yarn.lock
This PR allows to colorize icons as a prop in the from svg generated icon component.
=> Disabled button style

package.json, packages/playground/webpack.config.js, yarn.lock
This PR adds the css-minimizer-plugin to webpack
Tasks:
=> 159-css-minimizer

packages/components/src/ButtonWithIcon.tsx, packages/components/src/LabeledLink.tsx, packages/playground/src/app/Header/ShareSubmenu.tsx, packages/playground/tailwind.config.js
=> 177-sharing-submenu-placeholder

.cspell.json, packages/components/src/console/ConsoleMessage.tsx, packages/ink-editor/src/index.tsx, packages/ink-editor/src/utils/configureLanguage.ts, packages/ink-editor/src/utils/startRustAnalyzer.ts, packages/playground/__tests__/app/Editor.test.tsx, packages/playground/src/app/index.tsx, packages/playground/src/context/app/reducer.ts
=> 12-monaco-custom-theme

packages/components/src/ButtonWithIcon.tsx, packages/playground/src/app/Header/index.tsx
=> 185-button-icon-color

packages/components/src/ButtonWithIcon.tsx, packages/ink-editor/src/index.tsx, packages/playground/src/app/index.tsx
=> 187-frontend-bugfixing

packages/ink-editor/src/index.tsx, packages/playground/src/app/index.tsx
This fixes #263 by using switching to the uncontrolled version of monaco editor and updating the Editos Content by using the monaco editor API.
=> Fix selected text for gists

compiler/Cargo.toml, crates/contract/Cargo.toml
Upgrades ink! 3.0.0 -> ink! 3.2.0
=> Upgrade to ink! to Version 3.2.0

crates/rust_analyzer_wasm/src/lib.rs, packages/ink-editor/src/utils/startRustAnalyzer.ts
Improves the overall structure of Rust Analyzer WASM implementation
=> Improve ra wasm

packages/playground/src/constants.ts
- Updates contracts ui link
- closes #325
=> update contracts ui link

.cspell.json, packages/playground/src/index.html
Adds the simpleAnalytics plugin to the HTML template of ink! Playground
=> add analytics to HTML template

packages/components/src/ButtonWithIcon.tsx, packages/playground/src/context/side-effects/compile.ts
- fixes some small css bug which led to "wobbling" spinners on buttons in Firefox
- changes Terminal status message "Compilation hast started..." to "Compiling Smart Contract..."
=> fix tailwind css

packages/playground/src/index.html
Adds crossorigin tag to simple-anmalytics script to fix CORS issue.
=> add crossorigin tags for analytics script

packages/ink-editor/src/utils/configureLanguage.ts
Just a small fix preventing a bunch of console errors in the Frontend (.range undefined)
=> Fix console errors

.cspell.json, packages/playground/src/app/Header/index.tsx, packages/playground/src/assets/format.svg, packages/playground/src/symbols.ts
Adds the correct svg icon to the new formatting button
=> Format icon

.github/workflows/docker.yml
Introduces automatic versioning/tagging to `ink-playground` docker image
=> Ci automatic build number

Cargo.lock, crates/sandbox/src/example_code.rs
Updates Smart Contract code for testing to ink! 4
=> update Smart Contract code

packages/ink-editor/src/example-code.ts
ink! 4 should use the ink! 4 flipper example code as default code.
=> provide correct flipper example

Cargo.lock, Dockerfile, crates/backend/Cargo.toml, crates/change_json/src/crate_graph_json.rs, crates/contract/Cargo.toml, crates/contract/lib.rs
=> ink to version 4.0

Cargo.lock, crates/backend/Cargo.toml, crates/change_json/Cargo.toml, crates/crate_extractor/Cargo.toml, crates/generate-bindings/Cargo.toml, crates/rust_analyzer_wasm/Cargo.toml, crates/sandbox/Cargo.toml
bump all rust deps, except rust analyzer
=> bump rust deps

.github/workflows/docker.yml
Update Sysbox to 0.6.1, attempt to debug https://github.com/paritytech/devops/issues/2526
=> sysbox -> 0.6.1

crates/backend/src/cli.rs
=> Remove short -h option from --host
