packages/playground/src/app/Editor/index.tsx, packages/playground/src/context/reducer.ts, packages/playground/src/context/side-effects.ts
We need global access to the monaco editor instance from all over the app: for compiling the source code, we need to obtain it first, later on, we need to replace the monaco editor workers with the Rust Analyzer web workers.
Them Monaco editor can be accessed via its [URI](https://microsoft.github.io/monaco-editor/api/classes/monaco.uri.html), by calling `monaco.editor.getModel(uri);` function from its API.
This PR:
- creates a URI field in the context state
- dispatches the editors URI to the context when monaco editor mounts
- retrieves the content of the monaco editor (the edited source code) for compile requests.
=> Access monaco editor by URI

.github/workflows/rust.yml, crates/backend/Cargo.toml, crates/sandbox/src/build_command.rs, crates/sandbox/src/example_code.rs, crates/sandbox/src/lib.rs
It turned out that the sandbox compilation tests did not run in CI. the reason for this was that they were behind a cargo feature flag, which was however declared in the wrong `Cargo.toml`. i decided it's better to omit the feature flag.
The PR
- removes the feature flag
and tries to make the actual test more waterproof by:
- [cleaning](https://github.com/paritytech/ink-playground/pull/109/files#diff-70f3cdfd262ed8e41549c5d0a795d32039a9ad50963a2e9ed0eaa74c2857cda5L103) the already compiled artefacts inside the `ink-backend` docker image. 
_Ideally the artefacts should not be present in the docker image. The complexity here is that we run the docker container in `--detach` mode (like in rust-playground). If the waiting mechanism fails for some reason we'd serve the old `contract.constract` …
=> Fix sandbox compilation test

packages/playground/webpack.config.js
closes #65 
Adds default environment variable on the plugin level, as explained here: https://webpack.js.org/plugins/environment-plugin/#usage-with-default-values
=> Fix yarn start (playground)

packages/components/__tests__/ButtonWithIcon.test.tsx, packages/components/src/ButtonWithIcon.tsx, packages/playground/src/app/Header/index.tsx
This PR introduces optional disabled and loading props to the ButtonWithIcon component and displays the button state accordingly.
A button with loading state is always disabled too.
Tasks:
=> ButtonWithIcon disabled and loading props

packages/components/src/console/ConsoleMessage.tsx
This PR contains a small fix for the icon positioning when compile result overflowing in console.
=> Fix icon position for overflowing compile result

Makefile, crates/rust_analyzer_wasm/src/lib.rs, packages/playground/src/app/Editor/utils/startRustAnalyzer.ts
Sets the FileId which is analyzed by rust analyzer to the correct value, replaces hardcoded values by constants.
remark: temporary fix, rust anlayzer should learn to read the id of the edited file automaticcally, but this requires more work....
=> set correct fileId, replace hardcoded ID by constants

Cargo.lock, crates/change_json/Cargo.toml, crates/change_json/src/change_json.rs, crates/change_json/src/crate_graph_json.rs, crates/crate_extractor/Cargo.toml, crates/rust_analyzer_wasm/Cargo.toml, crates/rust_analyzer_wasm/src/to_proto.rs, crates/rust_analyzer_wasm/tests/web.rs
This upgrade the Rust Analyzer depndencies in:
- change_json
- crate_extractor
- rust_analyzer_wasm
from version 0.0.78 to version 0.0.83 and fixes all breaking changes.
=> Upgrade ra

crates/change_json/src/change_json.rs, crates/change_json/src/lib.rs, crates/rust_analyzer_wasm/src/lib.rs
This PR adds:
- the `Find` trait to the `Change` in the `change_json` trait which allows to find a crate by its display name.
- automatic detection of the `CrateId` fo the `contract` crate in `rust_analyzer_wasm`
- conversion of the detected `CrateId` to its corresponding `FileId`
=> Detect the id of the contract crate automatically

.cspell.json, packages/playground/src/app/Editor/utils/configureLanguage.ts
Fixes the bug of vanishing markdown when hovering over certain keywords (e.g. bool).
=> Fix hover bug

crates/backend/src/main.rs
This PR adds the compression middleware to the actix web server.
=> Add compress middleware

crates/contract/Cargo.toml
This adds all ink! dependencies to the Cargo.toml file of the reference contract, so that their source code is provided to Rust Analyzer by the generated change.json file.
=> Add ink dependencies for all crates for change.json

compiler/Cargo.toml, compiler/Dockerfile, compiler/README.md
This PR:
- adds the Dockerfile from which we build the Docker image for Smart Contract compilation to the repo
- the Dockerfile is simplified by extending from the existing Docker image `paritytech/ink-ci-linux:production`
- adds all ink1 dependencies to the pre-build Smart Contract, so that they are available within the Docker image for future builds from `ink-playground`, where we cap network connection for security reasons
=> Add compiler Dockerfile

compiler/Cargo.toml, compiler/Dockerfile, crates/contract/Cargo.toml, crates/sandbox/src/example_code.rs
This PR:
- upgrades the ink! dependencies to Version 3.0 for compiler Docker image and rust analyzer
- now installs `cargo-contract` from crates.io instead of git
- removes `ink-experimental-engine`from `Cargo.toml` features
=> Upgrade ink 3 0

Makefile
Just a mini PR which removes the `generate-bindings` command from `playground-start` in the Makefile
=> no generate-bindings on playground-start

crates/rust_analyzer_wasm/src/lib.rs
This fixes #277 , the issue was the reference provider,: it called `find_all_refs` on the analysis snapshot of RA without restricting it scope. When editing e.g. a `bool` identifier, this tried to find a occurences of `bool` in the code base.
=> specify scope for find_all_refs

crates/rust_analyzer_wasm/src/lib.rs, packages/ink-editor/src/utils/startRustAnalyzer.ts
Currently Firefox crashes while loading Rust Analyzer WASM as reported in #310 . The crash is due to the data transfer of a huge String from the React code to the WASM WebWorker containing all the ink! projects source code and its dependency graph. 
This crashing can be prevented by passing an ArrayBuffer (`Vec<u8>`) instead of an `String` to the WASM worker thread, since modern Browser are optimized for passing ArrayBuffers between Worker threads(https://developer.chrome.com/blog/workers-arraybuffer/). 
This is done by:
- use [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) to convert the String into an ArrayBuffer in the React TypeScript code
- use [String::from_utf8_lossy](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy) to …
=> Use array buffer

Makefile, packages/playground/src/index.html, packages/playground/webpack.config.js
- fixes the broken analytics URL which was reported in: https://github.com/paritytech/web/issues/4
- defines the Analytics Backend URL through a .env variable
=> use ENV variable to define analytics URL

crates/rust_analyzer_wasm/src/lib.rs
Fixes the unresolved-macro error currently showing up on staging by disabling `unresolved-macro-call` in diagnostics settings of Rust Analyzer.
=> diable unresolved-macro-call errors

.github/workflows/docker.yml
Upddates the outdated link in GitHub CI for the sysbox binary to https://downloads.nestybox.com/sysbox/releases/v0.5.2/sysbox-ce_0.5.2-0.linux_amd64.deb
=> update sysbox binary url

Cargo.lock, crates/contract/Cargo.toml
Update the reference contract and dependencies from ink! 4.0.0-alpha3 to ink! 4.0.0-beta.
#482
=> use ink! 4.0.0-beta for example contract

README.md
Just fixes a typo in the git clone command in the readme.
=> Remove duplicate `clone` subcommand

.github/workflows/makefile.yml, Makefile
I added a conditional install of `wasm-pack` to the Makefile, which should be relatively OS independent. 
I use the solution found here: https://itecnote.com/tecnote/check-if-a-program-exists-from-a-makefile/
Therefore, I also remove the `wasm-pack` install from the CI workflow.
=> Improve makefile
